language: python
python:
  - 3.5
env:
  - DJANGO_VERSION=1.11.6
install:
  - pip install coverage
  - pip install codecov
  - pip install -r requirements.txt
before_script:
  - ./manage.py migrate
script:
  - coverage run ./manage.py test
after_success:
  - codecov