# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171102_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='letters',
            field=models.FileField(blank=True, upload_to='letters'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='media',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
