# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20171103_0030'),
        ('database', '0003_auto_20171102_1211'),
    ]

    operations = [
    ]
