# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_merge_20171109_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
