# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsules',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('unlocks_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=30)),
                ('contributors', models.TextField()),
                ('recipients', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('location', models.TextField()),
            ],
        ),
    ]
