# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171019_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='contributors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.User'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='recipients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
